general.import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
opacity = 0.8

[font]
size = 12.0

[font.bold]
family = "CaskaydiaMono NFM"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaMono NFM"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaMono NFM"
style = "Italic"

[font.normal]
family = "CaskaydiaMono NFM"
style = "Regular"

#[window]
#opacity = 0.95
