log-file: /dev/null
input-file: ""
output-file: ""
ignore-dirs:
    - /proc
    - /dev
    - /sys
    - /run
ignore-dir-patterns: []
ignore-from-file: ""
max-cores: 16
sequential-scanning: false
show-apparent-size: false
show-relative-size: false
show-item-count: false
show-mtime: false
no-color: false
no-mouse: false
non-interactive: false
no-progress: false
no-unicode: false
no-cross: false
no-hidden: false
no-delete: false
follow-symlinks: false
profiling: false
const-gc: false
use-storage: false
storage-path: /tmp/badger
read-from-storage: false
summarize: false
top: 0
use-si-prefix: false
no-prefix: false
change-cwd: false
delete-in-background: false
delete-in-parallel: false
style:
    selected-row:
        text-color: "#1e1e2e"
        background-color: "#b4befe"
    progress-modal:
        current-item-path-max-len: 0
    use-old-size-bar: true
    footer:
        text-color: '#11111b'
        background-color: '#89b4fa'
        number-color: '#11111b'
    header:
        text-color: '#11111b'
        background-color: '#89b4fa'
        hidden: false
    result-row:
        number-color: '#89b4fa'
        directory-color: '#b4befe'
sorting:
    by: ""
    order: ""
